// js/print.js — Professional Print Helpers (Admission, Challan, Certificate)

/**
 * Opens a clean print window with branded header and the given HTML content.
 */
export function printDocument(title, bodyHtml, options = {}) {
  const {
    subtitle = 'Future Tech Public School',
    showDate = true
  } = options;

  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) {
    alert('Please allow pop-ups to print.');
    return;
  }

  const today = new Date().toLocaleDateString('en-PK', {
    day: '2-digit', month: 'long', year: 'numeric'
  });

  win.document.write(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <style>
    @page { size: A4; margin: 15mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #111;
      font-size: 13px;
      line-height: 1.45;
      padding: 10px 20px;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #C9A227;
      padding-bottom: 12px;
      margin-bottom: 18px;
    }
    .header .crest {
      display: inline-block;
      background: #0A1628;
      color: #C9A227;
      font-weight: 800;
      font-size: 14px;
      padding: 4px 10px;
      border-radius: 4px;
      margin-bottom: 6px;
    }
    .header h1 {
      font-size: 20px;
      color: #0A1628;
      margin: 4px 0;
    }
    .header .sub {
      font-size: 12px;
      color: #555;
    }
    .header .doc-title {
      font-size: 16px;
      font-weight: 700;
      color: #0A1628;
      margin-top: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .meta {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: #555;
      margin-bottom: 16px;
    }
    table.info {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
    }
    table.info td {
      padding: 6px 8px;
      border: 1px solid #ddd;
      vertical-align: top;
    }
    table.info td.label {
      width: 32%;
      background: #f7f7f7;
      font-weight: 600;
      color: #333;
    }
    .section-title {
      font-size: 13px;
      font-weight: 700;
      color: #0A1628;
      border-bottom: 2px solid #C9A227;
      padding-bottom: 3px;
      margin: 16px 0 8px;
    }
    .amount-box {
      background: #0A1628;
      color: #fff;
      text-align: center;
      padding: 12px;
      border-radius: 6px;
      margin: 12px 0;
    }
    .amount-box .label { font-size: 11px; opacity: 0.85; }
    .amount-box .value { font-size: 22px; font-weight: 700; color: #C9A227; }
    .status-paid {
      display: inline-block;
      background: #d1fae5;
      color: #065f46;
      padding: 3px 12px;
      border-radius: 999px;
      font-weight: 700;
      font-size: 12px;
    }
    .status-unpaid {
      display: inline-block;
      background: #fee2e2;
      color: #991b1b;
      padding: 3px 12px;
      border-radius: 999px;
      font-weight: 700;
      font-size: 12px;
    }
    .cert-body {
      text-align: center;
      padding: 30px 20px;
    }
    .cert-body h2 {
      font-size: 22px;
      color: #0A1628;
      margin-bottom: 8px;
    }
    .cert-body .student-name {
      font-size: 26px;
      font-weight: 700;
      color: #C9A227;
      margin: 16px 0;
      border-bottom: 2px solid #C9A227;
      display: inline-block;
      padding-bottom: 4px;
    }
    .signatures {
      display: flex;
      justify-content: space-between;
      margin-top: 50px;
      padding: 0 30px;
    }
    .signatures .sig {
      text-align: center;
      width: 180px;
    }
    .signatures .line {
      border-top: 1px solid #333;
      margin-bottom: 4px;
      padding-top: 4px;
      font-size: 12px;
    }
    .footer {
      margin-top: 30px;
      text-align: center;
      font-size: 10px;
      color: #888;
      border-top: 1px solid #eee;
      padding-top: 8px;
    }
    .no-print { display: none; }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="crest">FKC</div>
    <h1>${subtitle || 'Future Tech Public School'}</h1>
    <div class="sub">${subtitle && !String(subtitle).includes('Future Tech') && !String(subtitle).includes('Trading') && !String(subtitle).includes('Educational') ? 'Quest for Excellence' : (String(subtitle).includes('Trading') ? 'Learn | Trade | Succeed' : String(subtitle).includes('Educational') ? 'Skills | Knowledge | Excellence' : 'Qamber · Nurturing Minds, Building Futures')}</div>
    <div class="doc-title">${title}</div>
  </div>
  ${showDate ? `<div class="meta"><span>Date: ${today}</span><span>Generated by Future Tech School ERP</span></div>` : ''}
  ${bodyHtml}
  <div class="footer">
    Educating Minds • Building Futures • Empowering Traders<br>
    This is a computer-generated document.
  </div>
  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 300);
    };
  <\/script>
</body>
</html>
  `);
  win.document.close();
}

/** Build printable Admission Form HTML */
export function buildAdmissionPrint(adm, institutionName) {
  return `
    <div class="section-title">Student Information</div>
    <table class="info">
      <tr><td class="label">Full Name</td><td>${adm.name || '—'}</td></tr>
      <tr><td class="label">Date of Birth</td><td>${adm.dob || '—'}</td></tr>
      <tr><td class="label">Gender</td><td>${adm.gender || '—'}</td></tr>
      <tr><td class="label">B-Form / CNIC</td><td>${adm.bform || '—'}</td></tr>
      <tr><td class="label">Class / Course</td><td>${adm.className || adm.course || '—'}</td></tr>
      <tr><td class="label">Section / Batch</td><td>${adm.section || adm.batchName || '—'}</td></tr>
      <tr><td class="label">Admission Date</td><td>${adm.admissionDate || '—'}</td></tr>
      <tr><td class="label">Session</td><td>${adm.session || '—'}</td></tr>
    </table>

    <div class="section-title">Father / Guardian Information</div>
    <table class="info">
      <tr><td class="label">Father's Name</td><td>${adm.fatherName || adm.guardianName || '—'}</td></tr>
      <tr><td class="label">Father's CNIC</td><td>${adm.fatherCnic || '—'}</td></tr>
      <tr><td class="label">Phone</td><td>${adm.fatherPhone || adm.phone || '—'}</td></tr>
      <tr><td class="label">Occupation</td><td>${adm.fatherOcc || '—'}</td></tr>
    </table>

    <div class="section-title">Contact & Address</div>
    <table class="info">
      <tr><td class="label">Address</td><td>${adm.address || '—'}</td></tr>
      <tr><td class="label">City</td><td>${adm.city || '—'}</td></tr>
      <tr><td class="label">Primary Phone</td><td>${adm.phone || '—'}</td></tr>
    </table>

    <div class="signatures">
      <div class="sig"><div class="line">Parent / Guardian Signature</div></div>
      <div class="sig"><div class="line">Authorized Signature</div></div>
    </div>
  `;
}

/** Build printable Fee Challan HTML */
export function buildChallanPrint(challan, institutionName) {
  const isPaid = (challan.status || '').toLowerCase() === 'paid';
  return `
    <table class="info">
      <tr><td class="label">Student Name</td><td>${challan.studentName || '—'}</td></tr>
      <tr><td class="label">Class / Batch</td><td>${challan.className || challan.batchName || '—'}</td></tr>
      <tr><td class="label">Month</td><td>${challan.monthLabel || challan.month || '—'}</td></tr>
      <tr><td class="label">Challan No.</td><td>${challan.id || '—'}</td></tr>
      <tr><td class="label">Status</td><td>
        <span class="${isPaid ? 'status-paid' : 'status-unpaid'}">${isPaid ? 'PAID' : 'UNPAID'}</span>
      </td></tr>
    </table>

    <div class="amount-box">
      <div class="label">Amount Payable</div>
      <div class="value">Rs ${Number(challan.amount || 0).toLocaleString('en-PK')}</div>
    </div>

    ${isPaid && challan.paidOn ? `
      <p style="text-align:center;font-size:12px;color:#065f46;margin-top:8px">
        Paid on: ${new Date(challan.paidOn).toLocaleDateString('en-PK')}
      </p>
    ` : ''}

    <div class="signatures">
      <div class="sig"><div class="line">Received By</div></div>
      <div class="sig"><div class="line">Cashier / Accountant</div></div>
    </div>
  `;
}

/** Build printable Certificate HTML */
export function buildCertificatePrint(data, institutionName) {
  return `
    <div class="cert-body">
      <h2>Certificate of ${data.type || 'Completion'}</h2>
      <p style="margin:12px 0;font-size:14px">This is to certify that</p>
      <div class="student-name">${data.studentName || '—'}</div>
      <p style="margin:12px 0;font-size:14px;max-width:480px;margin-left:auto;margin-right:auto;line-height:1.6">
        ${data.body || `has successfully completed the requirements of <strong>${data.course || data.className || 'the program'}</strong> at ${institutionName}.`}
      </p>
      <p style="margin-top:20px;font-size:13px;color:#555">
        Date: ${data.date || new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' })}
      </p>
    </div>

    <div class="signatures">
      <div class="sig"><div class="line">Principal / Director</div></div>
      <div class="sig"><div class="line">Authorized Signature</div></div>
    </div>
  `;
}


export function buildIdCardPrint(student, institutionName) {
  const name = student.name || '—';
  const cls = student.className || student.course || student.batchName || '—';
  const phone = student.phone || student.guardianContact || '—';
  const guardian = student.guardianName || student.fatherName || '—';
  const id = (student.id || '').slice(0, 8).toUpperCase();
  return `
    <div style="display:flex;justify-content:center;padding:1rem;">
      <div style="width:340px;border:3px solid #C9A227;border-radius:14px;overflow:hidden;font-family:Inter,Arial,sans-serif;box-shadow:0 4px 20px rgba(0,0,0,0.12);">
        <div style="background:#0A1628;color:#fff;padding:12px 14px;text-align:center;border-bottom:3px solid #C9A227;">
          <div style="font-size:11px;letter-spacing:1.5px;color:#E8D48B;font-weight:600;">STUDENT IDENTITY CARD</div>
          <div style="font-size:14px;font-weight:800;margin-top:4px;">${institutionName}</div>
        </div>
        <div style="padding:16px 14px;background:#fff;">
          <div style="display:flex;gap:12px;align-items:flex-start;">
            <div style="width:72px;height:88px;background:#EEF1F5;border:2px solid #C9A227;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#8B93A1;font-size:10px;text-align:center;flex-shrink:0;">PHOTO</div>
            <div style="flex:1;font-size:12px;line-height:1.55;">
              <div style="font-size:15px;font-weight:800;color:#0A1628;margin-bottom:6px;">${name}</div>
              <div><strong>ID:</strong> ${id}</div>
              <div><strong>Class/Course:</strong> ${cls}</div>
              <div><strong>Guardian:</strong> ${guardian}</div>
              <div><strong>Phone:</strong> ${phone}</div>
            </div>
          </div>
        </div>
        <div style="background:#0A1628;color:#E8D48B;padding:8px 14px;font-size:10px;text-align:center;letter-spacing:0.5px;">
          Quest for Excellence · Valid for current session
        </div>
      </div>
    </div>
  `;
}
